version: "3"
services:
  lucas-nginx:
    build: ./nginx/frontend
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: production
    volumes:
      #- ./nginx/frontend:/app
      #- ./nginx/frontend/node_modules:/app/node_modules
      - ./nginx/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      #- ./nginx/frontend/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh # Script to autoreload Nginx when certs are renewed
    #depends_on:
    #  - lucas-backend
    #  #  condition: service_healthy

  lucas-backend:
    restart: unless-stopped
    build: ./backend/build
    ports:
      - "8989:8989"
    environment:
      lucas.db.host: lucas-mysqldb
      lucas.db.username: ${DATABASE_USER_NAME}
      lucas.db.password: ${DATABASE_USER_PASSWORD}
      lucas.db.port: 3307
      lucas.db.name: ${DATABASE_NAME}
    depends_on:
      lucas-mysqldb:
        condition: service_healthy
    #healthcheck:
    #  test: curl -f http://lucas-backend:8989/actuator/health || exit 1
    #  interval: 7s
    #  retries: 10
    #  timeout: 7s
    deploy:
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.20'

  lucas-mysqldb:
    image: mysql:latest
    ports:
     - "3307:3307"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 7s
      timeout: 7s
      retries: 15
    deploy:
      resources:
        limits:
          cpus: '0.25'
        reservations:
          cpus: '0.20'

  lucas-certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${CERTBOT_EMAIL} -d ${APPLICATION_DOMAIN} --agree-tos
