version: "3"
services:
  lucas-frontend:
    restart: unless-stopped
    build: ./frontend
    expose: 
      - '3000'
    ports:
      - '3000:80'
    volumes:
      - ./frontend/:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      NODE_ENV: production
    depends_on:
      lucas-backend:
        condition: service_healthy
      lucas-mysqldb:
        condition: service_healthy

  proxy:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - lucas-frontend

  lucas-backend:
    restart: unless-stopped
    build: ./spring-boot-backend
    ports:
      - "8989:8989"
    environment:
      lucas.db.host: lucas-mysqldb
      lucas.db.username: lucas
      lucas.db.password: DPgKaUuqTpvzYKzaOsLTmzIuGulgjfnWToe
      lucas.db.port: 3307
      lucas.db.name: lucasdb
    depends_on:
      lucas-mysqldb:
        condition: service_healthy
    healthcheck:
      test: curl -f http://lucas-backend:8989/actuator/health || exit 1
      interval: 5s
      retries: 10
      timeout: 5s

  lucas-mysqldb:
    image: mysql:latest
    #volumes:
    #  -  /home/user/Desktop/db:/var/lib/mysql
    ports:
     - "3307:3307"
    environment:
      MYSQL_DATABASE: lucasdb
      MYSQL_ROOT_PASSWORD: YiXRiugmWioKFyZTyTMwMMBOkMuMJNgtYCN
      MYSQL_USER: lucas
      MYSQL_PASSWORD: DPgKaUuqTpvzYKzaOsLTmzIuGulgjfnWToe
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 7s
      timeout: 7s
      retries: 15
