version: "3"
services:
  lucas-frontend:
    image: udvattila99/lucas-eu-frontend
    restart: unless-stopped
    expose: 
      - '3000'
    ports:
      - '3000:80'
    environment:
      NODE_ENV: production
    depends_on:
      - lucas-backend

  lucas-backend:
    image: udvattila99/lucas-eu-backend
    restart: unless-stopped
    ports:
      - "8989:8989"
    environment:
      lucas.db.host: lucas-mysqldb
      lucas.db.username: lucas
      lucas.db.password: DPgKaUuqTpvzYKzaOsLTmzIuGulgjfnWToe
      lucas.db.port: 3307
      lucas.db.name: lucasdb
    depends_on:
      lucas-mysqldb:
        condition: service_healthy

  lucas-mysqldb:
    image: mysql:latest
    ports:
     - "3307:3307"
    environment:
      MYSQL_DATABASE: lucasdb
      MYSQL_ROOT_PASSWORD: YiXRiugmWioKFyZTyTMwMMBOkMuMJNgtYCN
      MYSQL_USER: lucas
      MYSQL_PASSWORD: DPgKaUuqTpvzYKzaOsLTmzIuGulgjfnWToe
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 7s
      timeout: 7s
      retries: 15
