server:
  port: 8989
#spring:
#  batch:
#    jdbc:
#      initialize-schema: always
#  application:
#    name: lucas_backend
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    generate-ddl: false
#===== Actuator HEALTH properties ======#
management:
  endpoints:
    web:
      exposure:
        include: health
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/lucasdb
