version: "3"
services:
  lucas-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      NODE_ENV: production
    volumes:
      - ./nginx/startup.sh:/startup.sh
      - ./nginx/build:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./nginx/build:/var/www/lucasimageanalyzer.com
      - ./certbot/www:/var/www/html

  lucas-backend:
    restart: unless-stopped
    build: ./backend
    ports:
      - "8989:8989"
    environment:
      lucas.db.host: lucas-mysqldb
      lucas.db.username: ${DATABASE_USER_NAME}
      lucas.db.password: ${DATABASE_USER_PASSWORD}
      lucas.db.port: 3307
      lucas.db.name: ${DATABASE_NAME}

      # Setting up the email sender
      spring.mail.host: ${SPRING_MAIL_HOST}
      spring.mail.port: ${SPRING_MAIL_PORT}
      spring.mail.username: ${SPRING_MAIL_USERNAME}
      spring.mail.password: ${SPRING_MAIL_PASSWORD}

      # Disabling the sql display on the output
      spring.jpa.show-sql: false
      spring.jpa.properties.hibernate.format_sql: false
    depends_on:
      lucas-mysqldb:
        condition: service_healthy

  lucas-mysqldb:
    image: mysql:8.0-debian
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER_NAME}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
      MYSQL_TCP_PORT: 3307
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 7s
      timeout: 7s
      retries: 15

  lucas-certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    command: certonly --webroot -w /var/www/html --force-renewal --email ${CERTBOT_EMAIL} -d ${APPLICATION_DOMAIN} --agree-tos