version: '3'
services:
  lucas-image-server:
    image: udvattila99/image-server:latest
    restart: unless-stopped
    ports:
      - '$USE_PORT_FOR_SERVER:$USE_PORT_FOR_SERVER'
    environment:
      USE_PORT_FOR_SERVER: $USE_PORT_FOR_SERVER
    volumes:
      - ./media/:/app/media
