apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image
        ports:
        - containerPort: 8989
        env:
        - name: LUCAS_DB_HOST
          value: database
        - name: LUCAS_DB_USERNAME
          value: user
        - name: LUCAS_DB_PASSWORD
          value: mysql-db-password
        - name: LUCAS_DB_PORT
          value: 3306
        - name: SPRING_MAIL_HOST
          value: mail-host-server
        - name: SPRING_MAIL_PORT
          value: 587
        - name: SPRING_MAIL_USERNAME
          value: example@gmail.com
        - name: SPRING_MAIL_PASSWORD
          value: secret-code
        - name: SPRING_JPA_SHOW_SQL
          value: false
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: false
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8989
    targetPort: 8989