apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  volumes:
    - name: cert-volume
      persistentVolumeClaim:
        claimName: certbot-pvc
  containers:
    - name: debug
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
        - name: cert-volume
          mountPath: /certs